### ISSUE TITLE
TypeError: Cannot read property 'jvm' of undefined

### ISSUE THREAD

**Issue by satazor** [pm2-hive/pm2-elasticsearch#3]
Occasionally I get this error:

```
pm2-elasticsearch-1 (err): TypeError: Cannot read property 'jvm' of undefined
pm2-elasticsearch-1 (err):     at Request._callback (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/lib/stats.js:91:30)
pm2-elasticsearch-1 (err):     at Request.self.callback (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:199:22)
pm2-elasticsearch-1 (err):     at emitTwo (events.js:87:13)
pm2-elasticsearch-1 (err):     at Request.emit (events.js:172:7)
pm2-elasticsearch-1 (err):     at Request.<anonymous> (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:1036:10)
pm2-elasticsearch-1 (err):     at emitOne (events.js:82:20)
pm2-elasticsearch-1 (err):     at Request.emit (events.js:169:7)
pm2-elasticsearch-1 (err):     at IncomingMessage.<anonymous> (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:963:12)
pm2-elasticsearch-1 (err):     at emitNone (events.js:72:20)
pm2-elasticsearch-1 (err):     at IncomingMessage.emit (events.js:166:7)
```

Just wanted to let you know, so that it can be solved. Nothing really serious.

**Comment by satazor** [comment]
Bump.

**Comment by vmarchaud** [comment]
The module has been re-wrote, this should be fixed, please use the latest version ;)

**Comment by satazor** [comment]
@vmarchaud I'm still getting a few errors even after upgrading, shall I create a new issue?

```
TypeError: Cannot read property 'avg' of undefined
    at Request._callback (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/lib/stats.js:167:73)
    at Request.self.callback (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/analyzer/.pm2/node_modules/pm2-elasticsearch/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
```

**Comment by vmarchaud** [comment]
@satazor You must not be on the latest version since [lib/stats](https://github.com/pm2-hive/pm2-elasticsearch/blob/master/lib/stats.js) file has only 147 lines.

**Comment by satazor** [comment]
Alright, I will check it out, thanks
